### PR TITLE
GitHub is not Github

### PR DESCRIPTION
**Pull request by siketyan**
Fixed typo.

### CODE REVIEW

**Review by soshiharami — APPROVED** [review]

**Review by shun-shobon — APPROVED** [review]

**Review by loxygenK — APPROVED** [review]

**Review by laminne — APPROVED** [review]
**_Approve_**

**Review by kawaemon — APPROVED** [review]
Case Police

**Comment by siketyan** [comment]
@onokatio

**Comment by onokatio** [comment]
いや草

**Pull request merged**
